apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-proxy-config
  labels:
    app: {{ .Chart.Name }}-proxy-{{ .Values.proxy.alias }}
data:
  proxy-config.json: |
    {
      "private": [
        {{- range $index, $config := .Values.proxy.configs }}
        {{- if $index }},{{- end }}
        {
          "method": "{{ $config.method }}",
          "origin": "{{ $config.origin }}",
          "path": "{{ $config.path }}"
          {{- if $config.auth }},
          "auth": {
            "scheme": "{{ $config.auth.scheme }}"
            {{- if $config.auth.token }},
            "token": "{{ $config.auth.token }}"
            {{- end }}
            {{- if $config.auth.username }},
            "username": "{{ $config.auth.username }}"
            {{- end }}
            {{- if $config.auth.password }},
            "password": "{{ $config.auth.password }}"
            {{- end }}
          }
          {{- end }}
        }
        {{- end }}
      ]
    }